### ISSUE TITLE
Write test for drf-flex-fields

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#17]

**Comment by jacqui** [comment]
Two of our serializers needed support for `expandable_fields`:

* Only the `PressPassEntitlmentSerializer` and `PressPassInvitationSerializer` inherit from `FlexFieldsModelSerializer`
* I switched the rest of them back to inheriting from `serializers.ModelSerializer`
* I've added tests for the retrieve & list API endpoints for entitlements, and the retrieve endpoint for the invitation
* and I made sure to run `inv format` and `inv pylint` on this code

I then responded briefly to the feedback:

* [Squarelet PR 36 - Flex Fields](https://github.com/MuckRock/squarelet/pull/36)
