### ISSUE TITLE
Fix membership queryset to Mitch's specifications

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#19]
> * The `get_viewable` method should return all viewable memberships for the user, not just memberships for that user  - so it should be `return self.filter(...` not `return user.memberships.filter(...` as in the view, where we only want memberships for the user we have specified in the URL.  So in the view, with this method, it would be something along the lines of `user.memberships.get_viewable(self.request.user)`
> 
> * `private=False` is on the Organization, not the membership, so it should be `organization__private=False`
> 
> * `Q(organization__users=self.request.user)` should be `Q(organization__users=user)` - we want memberships that the passed in user are a part of.  `self` here is the queryset, which does not have a request attribute - that only exists at the view level.

**Comment by jacqui** [comment]
I've made these changes - and I've read over the docs and the related code in the API so I actually understand what's going on. I've run the test suite too. Next I need to write a test for a queryset, which I haven't done before... so I'm off to find examples of how people do that properly in a django app first :)
