### ISSUE TITLE
Use get_viewable method in get_queryset return

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#20]
See [here](https://github.com/MuckRock/squarelet/pull/32/files/5bb4df8d964b3384355753b0b6d5a551756ebf3b#diff-59700b28fbdf54af536464dac7799d0eR124-R129)

**Comment by jacqui** [comment]
I updated the call in the viewset to use this method that got defined in the queryset. This is part of [squarelet PR 32](https://github.com/MuckRock/squarelet/pull/32).
