### ISSUE TITLE
❓Remove uuid from extra_kwargs in nested invitation serializer

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#21]

**Comment by TylerFisher** [comment]
https://github.com/MuckRock/squarelet/pull/32/files/ba4ac9c9846a5d3099256148bf87a7f56a9d67ec#diff-5bb86e94b89593b2247912ae8f7859c2R174-R193

**Comment by jacqui** [comment]
Hey, I just noticed this had its own issue, and I addressed it in Issue #18 - so pardon my copy & paste:

> I had added the UUID for an invitation to the data returned for it (PressPassNestedInvitationSerializer) by the API. Mitch said this shouldn't have been added, so I removed it... but I'm not sure how we'll get the UUID for the invitation without this change. Note that we need the UUID in order to accept/reject/update invitations. And that's, as with everything I say, as far as I know at least 🤓✌️😉

Basically, it's easy enough for me to add or remove this one line of code from the serializer. I just want to know how do we get the unique ID for an invite in order to accept or reject it?

**Comment by TylerFisher** [comment]
Mitch says this is okay.
