### ISSUE TITLE
Integrate Stripe to facilitate subscribing to paid plans

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#23]
Stripe needs to create a token for use in Squarelet so that we can subscribe to paid plans

**Comment by jacqui** [comment]
How to create a token: https://stripe.com/docs/js/tokens_sources/create_token?type=cardElement

**Comment by jacqui** [comment]
This is in progress, but so far:

* differentiate between paid and free plans
* paid plans: subscribe opens a modal for credit card info
* credit card modal integrates with Stripe using card elements
* stripe integration includes request to get a form

To do:

* verify correct "publishable API key" for stripe-js
* stripe Charges API vs Payment Intents (https://stripe.com/docs/js/tokens_sources) - US/Canada vs Global
* hook up paid version of `createSubscription` including token

Work in progress can be found in the feature branch [feature/manage-paid-plans-stripe](https://github.com/news-catalyst/presspass-frontend/tree/feature/manage-paid-plans-stripe)
