### ISSUE TITLE
Synthesize subscription ID for stores

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#26]
`${planID}-${organizationID}` or something

**Comment by jacqui** [comment]
So I actually did this first thing this morning then I realized that we actually need the real subscription ID - it's how we unsubscribe:

```
DELETE /pp-api/organizations/{organization_uuid}/subscriptions/{id}/ pp-api_organizations_subscriptions_delete
```

I've saved the work though just in case [in a feature branch called feature/subscription-composite-key](https://github.com/news-catalyst/presspass-frontend/compare/develop...feature/subscription-composite-key?expand=1).
