### ISSUE TITLE
PK error trying to subscribe to an existing plan

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/presspass-frontend#28]
For some reason I'm getting this error:

```
{"plan":["Invalid pk \"6\" - object does not exist."]}
```

when I try to subscribe to a free plan. Example request:

```
curl 'http://dev.presspass.com/pp-api/organizations/c7e04390-6fa6-4c60-bed7-28f9fbd98375/subscriptions/' 
-H 'Content-Type: application/json' 
-H 'Accept: */*' -H 'Origin: http://dev.presspass.com:3000' 
--data-binary '{"plan":6}' --compressed --insecure
```

The API returned this for the plan in question:

```
{
  "id": 6,
  "name": "Beta",
  "slug": "beta",
  "minimum_users": 1,
  "base_price": 0,
  "price_per_user": 0,
  "public": false,
  "annual": false,
  "for_individuals": true,
  "for_groups": false,
  "entitlements": [
    4
  ]
}
```

**Comment by jacqui** [comment]
Aha, I found why this is happening, but resolving it is a question for Mitch, I think. Basically our list of plans seems to include items that can't be subscribed to. 

@TylerFisher I can't imagine this is intentional, right? But I'm not sure how to best resolve it.

Given that:

* `plans` are loaded via `GET /pp-api/plans` and returns an apparently full set of plans
* if the plan is (current implementation) free and not already subscribed-to, onclick try subscribing by `POST`ing the `{plan: ID}` to the `create-subscription` endpoint

Here's what happens when you try to subscribe:

* `POST`ing subscriptions limits available plans to a [queryset (links to serializer ref)](https://github.com/MuckRock/squarelet/blob/api/squarelet/organizations/serializers.py#L302) of `Plan.objects.choices(organization)`

In my example, only 2 plans are including in that queryset for my fake organization:

```
In [11]: org                                                                                                                                                                                                
Out[11]: <Organization: BBC News>

In [12]: Plan.objects.choices(org)                                                                                                                                                                          
Out[12]: <PlanQuerySet [<Plan: Free>, <Plan: Organization>]>
```

Plan id#6 in my database is the `Admin` plan which isn't included here.

Questions:

* should the `/pp-api/plans` list be restricted to `Plan.object.choices(organization)`?
* should there be some kind of filter query param for listing available plans instead?
* is this `choices` queryset correct for creating subscriptions?

**Comment by mitchelljkotler** [comment]
So there are a couple things we'd want to filter on:
1. Whether we want individual or group plans (If you are not planning on support individual subscriptions, we can skip that)
2. Whether the plan is public or not - do you have a need to support private plans? (We use this basically to give certain customers special discounted plans)
3. We also need to differentiate between MuckRock and PressPass plans

If you are not supporting individuals or private plans, we can just make a filter that returns all public, PressPass plans (for groups, but all PressPass plans should be group only).  If you do want to support private plans or individual subscriptions, we can make a filter where you pass the organization ID and it returns the correct plans for that organization.  We could also add a filter to specify MuckRock or PressPass plans, but a default of PP should suffice for you - only need MR plans if we plan on using the API for anything from our side.

**Comment by TylerFisher** [comment]
1. I think we may end up having individual subscriptions. I'd like to build the option.
2. I could also imagine supporting private plans. 
3. Agreed.

Given that, I think passing the organization ID should work, and default to only send PressPass plans.

**Comment by TylerFisher** [comment]
Mitch has addressed.
