### ISSUE TITLE
List of organizations on search page should only display public organizations

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#40]
e.g. private, individual organizations should not be available. This is probably a Squarelet issue, but we could also filter things out on the front-end.

**Comment by jacqui** [comment]
I didn't see a way to filter organizations in the squarelet endpoint, so for now (at least) I've added filtering to the organization list page; this is in PR #36 

Now that I'm typing this I realize that we'll have to handle paginated results. I'll open another issue for that so we can prioritize appropriately.
