### ISSUE TITLE
Rename 'website' as 'login url'

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/presspass-frontend#47]
From our instructions for developers:

>> Website: the login route to your application. The PressPass dashboard will use this URL to log users in to your application automatically when they click on your application.

We briefly discussed this before, @TylerFisher, but I'll rename the label for this field on the front-end to something more obvious, like "Login URL" - good?

**Comment by TylerFisher** [comment]
Yup, I think that'll be good. Maybe also some help text to explain what we mean by Login URL. Something like "This should be the route that kicks off the OAuth process in your application."

**Comment by jacqui** [comment]
This is done in PR #48
