### ISSUE TITLE
Entitlements don't seem properly scoped: add user filter to endpoint

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/presspass-frontend#53]
Once I realized the `EntitlementsList` page had a bug and was only displaying a single entitlement, then fixed it, it became clear that this list of entitlements doesn't make a lot of sense. 

I'm not sure what entitlements a brand new PressPass user (individual org at this point) should see. I guess this relates to the issue you wrote up about default plan(s) for individuals @TylerFisher.

What do you think?

**Comment by TylerFisher** [comment]
Discussed with Mitch: we'll need to add a user parameter to the entitlements endpoint to get a list of all entitlements the user can access based on their plans.

This line is going to be the key one: https://github.com/MuckRock/squarelet/blob/api/squarelet/organizations/querysets.py#L100. This should find entitlements that are a part of each plan a user is subscribed to. It'll be a somewhat complex query, but it's what we need to get this view right.

**Comment by jacqui** [comment]
Just to connect the dots, I've opened a draft PR aiming to address this https://github.com/MuckRock/squarelet/pull/46 and hoping you can have a look to sanity check it @TylerFisher. Thank you :)

**Comment by TylerFisher** [comment]
Done.
