### ISSUE TITLE
Validation step for new OAuth clients

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#57]

**Comment by TylerFisher** [comment]
Feels like the right answer here, at least initially, is to replace the current system of registering a client whenever you want with more of an application process. Perhaps an Airtable form you fill out to request access to PressPass as an OAuth provider.

**Comment by jacqui** [comment]
And then we review those submissions, and if approved someone on the team enters the info into the django admin and emails a notification?
