### ISSUE TITLE
Seeing multiple requests for the same thing

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#62]
For example, on the manage organization page, I see:

- 2 requests for invitations
- 3 requests for plans
- 6 requests for subscriptions

<img width="1003" alt="Screen Shot 2020-04-01 at 4 15 44 PM" src="https://user-images.githubusercontent.com/1077075/78182420-28367380-7434-11ea-958b-a9eb3b17d4dc.png">

**Comment by jacqui** [comment]
Addressed in PR #63  - think I got them all, but please do let me know if you spot any more crazy api hits.
