### ISSUE TITLE
Change email functionality

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#80]
We do need the ability to change email addresses. I think this can just go in the manage profile section and become part of the same request.

**Comment by jacqui** [comment]
I've added this into the front-end, but it appears that changing an email address isn't supported in the API. I asked how to go about this in the muckrock slack. I will probably submit a draft PR here with the work I've done so far but it's probably subject to change depending on how we end up needing to do this in the back-end.

the `email` field is read-only in the api. this test I wrote fails:

```
    def test_update_email(self, api_client, user):
        """Test updating a user's email"""
        api_client.force_authenticate(user=user)
        email = "new@example.org"
        assert user.email != email
        response = api_client.patch(
            f"/pp-api/users/{user.individual_organization_id}/", {"email": email}
        )
        assert response.status_code == status.HTTP_200_OK
        user.refresh_from_db()
        assert user.email == email
```
