### ISSUE TITLE
Email endpoints on Squarelet

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/presspass-frontend#83]
Implement endpoint on Squarelet leveraging `django-allauth` to enable users to add and remove email addresses from their accounts.

The endpoint should be mounted at `pp-api/users/<me or uuid>/email`. It can accept GET, POST, PATCH and DELETE.

When adding emails, verification emails should be sent.

**Comment by TylerFisher** [comment]
Taking Mitch's feedback into account, I reworked the Squarelet PR and the open PR here to follow a more RESTful design, but it's not done. Still can't figure out how to do the PATCH/DELETE requests through allauth in a way that makes sense.

**Comment by TylerFisher** [comment]
Talked to Mitch again, we're going to rewrite the viewset to more match the conventions of Django REST Framework, using serializers to validate the data. See the viewsets in the organization app, especially the invitation viewset, for examples on how this works.

**Comment by jacqui** [comment]
I've changed the email api's `update` to use a serializer validator.
