### ISSUE TITLE
Verifying email in squarelet results in email changed notification

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/presspass-frontend#99]
I think something's going wrong when trying to confirm/verify an email address as I'm getting the following notification email sent:

<img width="943" alt="Screen Shot 2020-04-28 at 1 25 22 pm" src="https://user-images.githubusercontent.com/3397/80443988-db22c000-8953-11ea-8c79-e93eb9592045.png">

this is after doing the following API call:

```
curl 'http://dev.presspass.com/pp-api/emails/jacqui27g@jacqui27g.com/' \
  -X 'PATCH' \
  -H 'X-CSRFToken: 4CZAhzUNkE1QHMCGd14e1Aw9hOmniBVgiH42RGMmkXvgSNEK2KWaXj7nYs4ApeKQ' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://dev.presspass.com:3000' \
  -H 'Referer: http://dev.presspass.com:3000/profile/welcome?email=jacqui27g@jacqui27g.com' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  --data-binary '{"email":{"email":"jacqui27g@jacqui27g.com","verified":true},"verify":true}' \
  --compressed \
  --insecure
```

(curl command copied from chrome network tab, trimmed for readability)

**Comment by jacqui** [comment]
I'm not sure what to do here... I reviewed the code used to update an email address and see it's meant solely for marking an email address as primary. 

https://github.com/MuckRock/squarelet/blob/feature/email-endpoints/squarelet/email_api/viewsets.py#L48-L102

@TylerFisher ~if the update email endpoint is only for this purpose... how do we verify an email address?~

~I'll keep digging and update this question / comment if I figure it out, but given our async scheduling I figured I'd log it.~

Okay an update: I think I figured out what has to happen here, after reviewing what `allauth` does. I'm not certain it's a good way to do it all in django or at least in terms of what MuckRock wants, so I haven't pushed it to `muckrock/squarelet`. 

Instead, I pushed it to my fork - you should be able to view the diff at https://github.com/MuckRock/squarelet/compare/feature/email-endpoints...jacqui:feature/email-endpoints

Sorry to split across another repo - I am trying to save us and MuckRock from reviewing something too early :) @TylerFisher do you mind looking at what I did here? 

* url is PUT or PATCH `/pp-api/verify/{key}/` 
* email confirmation message's 'verify your email' link updated to use the key instead of email address
* new viewset cobbled together by me (I'm getting these django tricks and practices... slowly) borrows heavily from [allauth email confirmation implementation](https://github.com/pennersr/django-allauth/blob/eaf6e96661a04ca1e9e8418ec1630646979823bd/allauth/account/views.py#L279-L301)

**Comment by TylerFisher** [comment]
My only comment is that I don't think the `update` method in the viewset will take a `user_uuid` argument since it's not mounted under the user router. Otherwise, this makes sense to me as a separate endpoint. It's working with a different model, so it can't work in the same viewset. Good catch.

**Comment by jacqui** [comment]
Okay thanks! I'll make that change and add a test, too. Then I'll push the changes to the email-endpoints PR in squarelet.
